server:
  servlet:
    session:
      timeout: 1200m
  port: 8099
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: frontend
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        - '*'

#spring:
#  mvc:
#  pathmatch:
#    matching-strategy: ant-path-matcher
#  datasource:
#    url: ${JDBC_DATASOURCE_URL}
#  jpa:
#    show-sql: true
#    generate-ddl: true