server:
  port: 8081
spring:
  application:
    name: ms-despesas
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        - '*'
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}