server:
  port: 8125
spring:
  application:
    name: api-gateway
management:
  endpoints:
    web:
      exposure:
        - '*'
  endpoint:
    gateway:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}